# Generated by Django 2.1.3 on 2018-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(max_length=25)),
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('appid', models.TextField(max_length=25, null=True)),
            ],
        ),
    ]
