# Generated by Django 2.1.3 on 2018-11-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessengerUser',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('appid', models.CharField(db_index=True, max_length=25, null=True)),
                ('context', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('is_productive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bot.UserActivity')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='useractivity',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.MessengerUser'),
        ),
        migrations.AddField(
            model_name='checkinstore',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UserActivity'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('uid', 'activity_name')},
        ),
    ]
