# Generated by Django 2.1.3 on 2018-11-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20181129_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengeruser',
            name='appid',
        ),
    ]
